#!/usr/bin/env bash

case $# in
  1)
    DAY=$1
    YEAR="2019"
  ;;
  2)
    DAY=$2
    YEAR=$1
  ;;
  3)
    DAY=$2
    YEAR=$1
    INPUT_PATH=$3
  ;;
  *)
    echo "Usage:
      ./run day
      ./run year day
      ./run year day /path/to/custom/puzzle/input.txt
    "

    exit 1
  ;;
esac

go run ./$YEAR/day$(printf "%02d" $DAY).go $INPUT_PATH